# CalcuateApp.h, GlobalHeader.h, Addition.c, Division.c, Multiply.c, Subtraction.c, CalculateApp.c
# Create Object file -> .o
# Create Target Binary Exec file-> Calulate

CalculateApp:
	clang CalculateApp.c -o ./Bin/CalculateApp

# CalcuateApp.o:
# 	clang -c ./CalculateApp.c -o ./Bin/Obj/CalculateApp.o

# Addition.o:
# 	clang -c ./Src/Addition.c -o ./Bin/Obj/Addition.o

# Division.o:
# 	clang -c ./Src/Division.c -o ./Bin/Obj/Division.o

# Multiply.o:
# 	clang -c ./Src/Multiply.o -o ./Bin/Obj/Multiply.o

# Subtraction.o:
# 	clang -c ./Src/Subtraction.c -o ./Bin/Obj/Subtraction.o

# CalcuateApp.out: ./Bin/Obj/CalculateApp.o ./Bin/Obj/Addition.o ./Bin/Obj/Division.o ./Bin/Obj/Multiply.o ./Bin/Obj/Subtraction.o
# 	clang -o ./Bin/CalculateApp.out ./Bin/Obj/CalculateApp.o ./Bin/Obj/Addition.o ./Bin/Obj/Division.o ./Bin/Obj/Multiply.o ./Bin/Subtraction.o

